### ISSUE TITLE
插件无法使用

### ISSUE THREAD

**Issue by luluwuxin** [CppCXY/VSCode-EmmyLua-Unity#10]
![image](https://user-images.githubusercontent.com/7278964/224644542-8f7a40a9-72a9-47b9-9434-020e8aba30ca.png)
EmmyLuaUnity：v1.22
VSCode:1.76.1

1.0.6版本可以使用

**Comment by CppCXY** [comment]
最新升级到 ,net7了如果无法运行应该可以在 
![image](https://user-images.githubusercontent.com/40318218/224646079-995ce58c-78c4-4e38-9d9c-543a19b2cbd1.png)
这里k看到一些报错

**Comment by luluwuxin** [comment]
[errlog.txt](https://github.com/CppCXY/VSCode-EmmyLua-Unity/files/10955310/errlog.txt)

**Comment by CppCXY** [comment]
应该找不到dotnet sdk 下的msbuild, 你有.net 7 吗

**Comment by luluwuxin** [comment]
刚安装的.net7  还是一样的报错

**Comment by CppCXY** [comment]
https://github.com/CppCXY/EmmyLua-Unity-LS
试图自己编译运行下这个程序

**Comment by luluwuxin** [comment]
.net7 编译成功

**Comment by CppCXY** [comment]
运行调试一下, 到registerdefault的时候看会不会报错

**Comment by luluwuxin** [comment]
没有报错

**Comment by CppCXY** [comment]
那现在插件还会报错吗, 或者你重启一下看看还会不会报错

**Comment by luluwuxin** [comment]
重启后，依然报一样的错

**Comment by 7ippo** [comment]
我也遇到了同样的错误

**Comment by CppCXY** [comment]
我以为没人用这个插件, 很多地方都是乱来的, 我降低版本看看.

**Comment by CppCXY** [comment]
更新了插件,降低了mslocator版本,试试看

**Comment by HungryHighness** [comment]
![1678709062956](https://user-images.githubusercontent.com/49775738/224696710-62b82212-8155-44b6-959f-11f6ec052195.jpg)
补全上没问题了，但是会报未定义

**Comment by CppCXY** [comment]
> ![1678709062956](https://user-images.githubusercontent.com/49775738/224696710-62b82212-8155-44b6-959f-11f6ec052195.jpg) 补全上没问题了，但是会报未定义

sumneko 插件自己有BUG, 生成的文档的CS定义缺少东西.

**Comment by luluwuxin** [comment]
版本1.2.3 可以正常使用

**Comment by wjf1616** [comment]
![image](https://user-images.githubusercontent.com/16534485/225496031-11bdd41f-d2cf-4e40-a914-d96380805ec0.png)

[Error - 10:38:44 AM] EmmyLuaUnity plugin for vscode. client: couldn't create connection to server.
Launching server using command /Users/jfwang/.vscode/extensions/cppcxy.emmylua-unity-1.2.3-darwin-x64/server/unity failed. Error: spawn /Users/jfwang/.vscode/extensions/cppcxy.emmylua-unity-1.2.3-darwin-x64/server/unity EACCES
