### ISSUE TITLE
请问Mac 可以执行吗

### ISSUE THREAD

**Issue by 37wjy** [CppCXY/VSCode-EmmyLua-Unity#15]
在Mac 上执行pull api 会出现这些错误, 请问这个要怎么更改才能正确执行

[15:30:46 DBG] [Failure] Msbuild failed when processing the file '<project_path>/Core.csproj' with message: The expression "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPlatformSDKLocation(Windows, 7.0)" cannot be evaluated. The value cannot be an empty string. (Parameter 'path')  /usr/local/share/dotnet/sdk/7.0.305/Microsoft.Common.CurrentVersion.targets

**Comment by CppCXY** [comment]
确保自己有.net sdk 7

**Comment by CppCXY** [comment]
整个项目最重要的是基于MSBUILD Locator, 他会从环境变量中找dotnet命令, 然后找到和编译时一样版本的dotnet sdk目录. 该项目是dotnet sdk7 编译的.

**Comment by 37wjy** [comment]
```shell
 % dotnet --info
.NET SDK:
 Version:   7.0.305
 Commit:    98e1b6c381

运行时环境:
 OS Name:     Mac OS X
 OS Version:  13.4
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.305/

Host:
  Version:      7.0.8
  Architecture: arm64
  Commit:       4b0550942d

.NET SDKs installed:
  7.0.305 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

这是我dotnet命令打出的信息

**Comment by CppCXY** [comment]
https://github.com/CppCXY/EmmyLua-Unity-LS
你可以试着编译这个项目, 然后替换掉插件里面的

**Comment by CppCXY** [comment]
dotnet publish -r osx-x64 -c Release --self-contained -o artifact /p:PublishSingleFile=true 
这个命令可以编译
