### ISSUE TITLE
在三分钟崩溃了五次

### ISSUE THREAD

**Issue by Contin-KD** [CppCXY/VSCode-EmmyLua-Unity#16]
The EmmyLuaUnity plugin for vscode.  server crashed 5 times in the last 3 minutes.  The server will not be restarted.  See the output for more information.

**Comment by CppCXY** [comment]
插件要求, 你电脑上有dotnet sdk 7, 是不是符合条件, 如果有问题你们可以自己编译https://github.com/CppCXY/EmmyLua-Unity-LS

**Comment by 1826872946** [comment]
我不知道该怎么操作

**Comment by CppCXY** [comment]
进群问: 583345382

**Comment by 1826872946** [comment]
解决了,打扰了,因为我的是Vs版本是.Net sdk 8,回滚下版本就ok了感谢

**Comment by CppCXY** [comment]
不久的将来我可能会升级到dotnet sdk8, 插件和dotnet版本强相关的原因是 微软的msbuildlocator只会寻找到和编译时一样版本的msbuild
