### ISSUE TITLE
Mac OS 无法提示

### ISSUE THREAD

**Issue by DemonicY** [CppCXY/VSCode-EmmyLua-Unity#17]
macOS unity Api无法提示。

**Comment by CppCXY** [comment]
![image](https://github.com/CppCXY/VSCode-EmmyLua-Unity/assets/40318218/f84e27b4-bfdf-4d86-8c69-5fcf9c8dbaa0)
这个满足了吗

**Comment by DemonicY** [comment]
<img width="612" alt="image" src="https://github.com/CppCXY/VSCode-EmmyLua-Unity/assets/61828737/96f8dd08-bae5-4fca-b8fa-26d613857a6e">

**Comment by CppCXY** [comment]
我没有mac环境, 我只能建议下载源码自己调试一下
