### ISSUE TITLE
配置名字错误

### ISSUE THREAD

**Issue by invokerw** [CppCXY/VSCode-EmmyLua-Unity#18]
代码中为`emmylua.unity.project_workspace` 配置为`mmylua.unity.project_sln` 是否写错了
<img width="719" alt="image" src="https://github.com/user-attachments/assets/75ecb5c4-9e81-4a13-a85a-866d1d557786">
![image](https://github.com/user-attachments/assets/dafa7352-f69d-4899-a6d4-20569f0d76c6)

**Comment by CppCXY** [comment]
确实写错了, 不过不影响基本使用, 默认以sln所在目录打开就能导出api了, 你可以选择提个PR修复这个错误

**Comment by invokerw** [comment]
> 确实写错了, 不过不影响基本使用, 默认以sln所在目录打开就能导出api了, 你可以选择提个PR修复这个错误

主要是我得lua放到外面。所以用这个配置没有生效 所以我才看到源码哈哈
