### ISSUE TITLE
按着操作步骤安装插件，使用报错

### ISSUE THREAD

**Issue by pigychan** [CppCXY/VSCode-EmmyLua-Unity#6]
<img width="1220" alt="88" src="https://user-images.githubusercontent.com/50442053/196658316-897e79c3-6aaa-47a0-b372-4eb1445991b5.PNG">

**Comment by CppCXY** [comment]
可能是电脑上环境不对，确保是win10 以上x64环境下拥有.net 6的运行环境

**Comment by pigychan** [comment]
感谢作者大佬的回复！我检查了下自己的电脑环境，确定是win10 x64 .net6.0.400的环境没错，请问除了文档中写的使用步骤以外，还需要另外做什么配置嘛，或者是可能存在一些坑点

**Comment by CppCXY** [comment]
你可以试着手动执行下对应的可执行文件，他在
C:\Users\你的用户名\.vscode\extensions\cppcxy.emmylua-unity-1.0.6-win32-x64\server
下叫unity.exe

**Comment by pigychan** [comment]
<img width="741" alt="89" src="https://user-images.githubusercontent.com/50442053/196682900-b83c1182-5b38-45a0-b575-6730cf2fa316.PNG">
执行后控制台显示如下

**Comment by CppCXY** [comment]
你电脑上没vs？

**Comment by pigychan** [comment]
visual studio嘛，是有的，我重新安装下试试看，需要勾选哪些特定的安装项嘛

**Comment by CppCXY** [comment]
https://github.com/CppCXY/EmmyLua-Unity-LS
或者你试试你能不能编译这个项目

**Comment by pigychan** [comment]
<img width="344" alt="90" src="https://user-images.githubusercontent.com/50442053/196688132-f4225cd1-7501-4ba8-9351-1f7bc6c26159.PNG">
在打开这个项目选择编译时，弹出了这个问题

**Comment by CppCXY** [comment]
找不到.net6 framework 自己安装一下最新的.net开发环境

**Comment by pigychan** [comment]
嗯嗯好的！感谢前辈给我提供了解题方向，感谢！

**Comment by pigychan** [comment]
看起来是vs的版本过低导致的，我在安装了.Net sdk6.0之后还是会出现找不到.net6 framework的问题，在网上看到需要把vs版本升级到2019
