### ISSUE TITLE
该插件主要依赖Unity根目录下的哪些文件夹

### ISSUE THREAD

**Issue by pigychan** [CppCXY/VSCode-EmmyLua-Unity#8]
现在Vscode下打开整个根目录，当项目规模较大时，搜索会卡顿，EmmyLua的解析也会比较慢

**Comment by pigychan** [comment]
<img width="1583" alt="92" src="https://user-images.githubusercontent.com/50442053/197162981-95810fba-0b20-4db9-be1f-59a7aa67c299.PNG">
想忽略掉一些用不上的文件夹，但怕影响到该插件对Unity Api的获取

**Comment by pigychan** [comment]
<img width="437" alt="93" src="https://user-images.githubusercontent.com/50442053/197163358-41fce780-afb7-489e-aa76-60ce891ee7e3.PNG">
想忽略掉一些用不上的文件夹，但怕影响到该插件对Unity Api的获取

**Comment by CppCXY** [comment]
也可以只打开lua文件所在的工作区, 然后在设置里面直接设置sln路径.

**Comment by pigychan** [comment]
Get，感谢前辈！
