### ISSUE TITLE
如何将自己编写的C#脚本，加入到插件的提示中

### ISSUE THREAD

**Issue by pigychan** [CppCXY/VSCode-EmmyLua-Unity#9]
<img width="44" alt="108" src="https://user-images.githubusercontent.com/50442053/197703787-57204bca-0d1d-4527-a0f2-df8cea021127.PNG">
<img width="45" alt="109" src="https://user-images.githubusercontent.com/50442053/197703803-3c2f23f0-e93a-46f2-93b1-e506bc754c0e.PNG">
自己编写的一些C#脚本，放在Unity根目录的Assets\Script中，我们的插件目前能够支持加入该路径下C#脚本的API提示嘛

**Comment by CppCXY** [comment]
插件只读Sln工程, 你需要做的事是把自己写的脚本加入sln中, 而指定sln的模式是无法监听到C# 文件变更的,所以只能重启插件

**Comment by pigychan** [comment]
收到，感谢前辈！
